# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: filebeat-config
#   namespace: logging
# data:
#   filebeat.yml: |-
#     filebeat.inputs:
#       - type: container
#         paths:
#           - /var/log/containers/*.log
#         processors:
#           - add_kubernetes_metadata:
#               in_cluster: true

#     output.elasticsearch:
#       hosts: ["http://elasticsearch:9200"]

#     logging.level: info

apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log

    processors:
      - add_kubernetes_metadata: ~

    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
